### ISSUE TITLE
Allow multipart user_data generated via either "template_cloudinit_config" or "cloudinit_config" terraform modules to be used if base64encoded and/or gzipped.

### ISSUE THREAD

**Issue by sharkymcdongles** [hetznercloud/terraform-provider-hcloud#167]
I have this simple test case:

**main.tf:**
```
data "template_cloudinit_config" "user_data" {
  gzip          = true
  base64_encode = true

  part {
    content_type = "text/cloud-config"
    content      = file("${path.module}/ubuntu-20.04.yaml")
  }

  part {
    content_type = "text/x-shellscript"
    content      = file("${path.module}/test.sh")
    filename     = "test.sh"
  }
}

output "cloud_init_output" {
  value = [data.template_cloudinit_config.user_data.rendered]
}

provider "hcloud" {
  token = "censored"
}

resource "hcloud_server" "lb" {
  count       = 1
  name        = "lb"
  server_type = "cx11"
  image       = "ubuntu-20.04"
  location    = "fsn1"
  user_data   = data.template_cloudinit_config.user_data.rendered
}
```

ubuntu-20.04.yaml:
```
#cloud-config
# set locale
locale: en_GB.UTF-8
# ensure time sync between all nodes
ntp:
  enabled: true
  ntp_client: chrony
# hides ssh keys in console
ssh_fp_console_blacklist: [ssh-dss, ssh-dsa, ssh-ed25519]
ssh_key_console_blacklist: [ssh-dss, ssh-dsa, ssh-ed25519]

# upgrade all packages and install necessary ones
package_upgrade: true
package_reboot_if_required: true
packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common
- build-essential
- libssl-dev
- make

# set random root password and disable password login for ssh
chpasswd:
  expire: false
  list: |
      root:RANDOM
ssh_pwauth: no

# create sre user with sudo privs and set autrhorized key
users:
- name: sre
  groups: sudo
  lock_passwd: true
  ssh_authorized_keys:
   - censored
  sudo: ['ALL=(ALL) NOPASSWD:ALL']
  shell: /bin/bash

# Configure Floating IP (Ubuntu 20.04 LTS)
# Not required when using https://github.com/costela/hcloud-ip-floater
#write_files:
#  - content: |
#      network:
#         version: 2
#         ethernets:
#           eth0:
#             addresses:
#             - ${floating_ip}/32
#    path: /etc/netplan/60-floating-ip.yaml
# Install Keepalived
runcmd:
- cd /root/
- wget http://www.keepalived.org/software/keepalived-2.1.2.tar.gz
- tar xvf keepalived-2.1.2.tar.gz
- cd keepalived-2.1.2
- ./configure
- make
- sudo make install


final_message: "The system is finally up, after $UPTIME seconds"

```

test.sh:
`echo test`

When it runs the user-data is not respected or used. If I don't gzip or base64 then it works as expected. Since cloud-init limits user-data to 16384bytes and can handle gzip and base64, it'd be highly beneficial to be able to pass this to the hcloud server creation.
